springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**

spring:
  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 구글이메일
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    include: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  servlet:
    session:
      store-type: redis

logging:
  level:
    springframework.security.web: trace
    com.example.blackmarket.security: trace