springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**

spring:
  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    include: local
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    session:
      store-type: redis