name: CD

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          
      - name: Grant execution permissions  
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew clean test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Grant execution permissions  
        run: chmod +x ./gradlew


      - name: Build with Gradle
        run: ./gradlew clean test

      - name: Deploy to Server
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -P 1024 -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r /root/black/build/libs/Blackmarket-0.0.1-SNAPSHOT.jar $USER@106.10.56.54:/tmp
          ssh -p 1024 -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USER@106.10.56.54 << EOF
          sudo systemctl stop webapp
          sudo mv /tmp/*.jar /app/webapp.jar
          sudo systemctl start webapp
          EOF
          rm -f private_key.pem
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      #- name: Notify Slack
      # if: failure()
      #  uses: 8398a7/action-slack@v3
      #  with:
      #    status: ${{ job.status }}
      #    fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.DEV_DEPLOY_SLACK_WEBHOOK_URL }}
